# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'DSCalendar' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DSCalendar
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'

  target 'DSCalendarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DSCalendarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
